RULES = {
    "OPENING_TEAM_MIN": 3,
    "CLOSING_TEAM_MIN": 3,
    "LUNCH_MAX_MINUTES": 60,
    "LUNCH_WINDOW_START": "12:00",
    "LUNCH_WINDOW_END": "15:00",
    "MAX_CONSECUTIVE_HOURS_NO_BREAK": 6,
    "MAX_DAILY_HOURS": 10,
    "STRICT_24H": True,
    "MAX_WEEKLY_35H": 35
}
