"""empty message

Revision ID: c14bd6993060
Revises: 20240926_update_close_times
Create Date: 2025-09-25 15:01:36.450288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14bd6993060'
down_revision = '20240926_update_close_times'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monday', sa.Date(), nullable=False),
    sa.Column('sunday', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planning_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planning_snapshot_monday'), ['monday'], unique=False)

    with op.batch_alter_table('base_shift', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_shift', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('planning_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planning_snapshot_monday'))

    op.drop_table('planning_snapshot')
    # ### end Alembic commands ###
