"""special openings

Revision ID: fae21a885fd2
Revises: c14bd6993060
Create Date: 2025-09-25 22:56:33.414253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae21a885fd2'
down_revision = 'c14bd6993060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_opening',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('open_time', sa.String(length=5), nullable=True),
    sa.Column('close_time', sa.String(length=5), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('sunday_mode', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('special_opening_shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('lunch_start', sa.String(length=5), nullable=True),
    sa.Column('lunch_end', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['opening_id'], ['special_opening.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sunday_available', sa.Boolean(), nullable=True))

    with op.batch_alter_table('planning_snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planning_snapshot', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('sunday_available')

    op.drop_table('special_opening_shift')
    op.drop_table('special_opening')
    # ### end Alembic commands ###
